enum actionTypes {
    FLICKR_IMAGES_LOADING = 'FLICKR_IMAGES_LOADING',
    FLICKR_IMAGES_SUCCESS = 'FLICKR_IMAGES_SUCCESS',
    FLICKR_IMAGES_FAIL = 'FLICKR_IMAGES_FAIL',
  }
  
  export default actionTypes;